# Generated by Django 3.2.11 on 2022-01-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('method', models.CharField(choices=[('Net', 'Net'), ('Hand', 'Hand')], max_length=5)),
                ('repeat', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=2)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.site')),
            ],
        ),
    ]
