# Generated by Django 3.2.11 on 2022-01-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='length_head_abdomen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='length_head_tegmina',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
