# Generated by Django 3.2.11 on 2022-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomygenus',
            options={'ordering': ['genus'], 'verbose_name_plural': 'Taxonomy genera'},
        ),
        migrations.AddField(
            model_name='observation',
            name='notes',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
