# Generated by Django 3.2.11 on 2022-02-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_alter_visit_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('site_name', 'date'), name='observations_visit_site_name_date_unique_relationships'),
        ),
    ]
