# Generated by Django 3.2.11 on 2022-01-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_refactor_observation_20220125_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=1024)),
            ],
        ),
    ]
