# Generated by Django 3.2.11 on 2022-01-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_observation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesname',
            old_name='latin_name',
            new_name='species',
        ),
    ]
