# Generated by Django 3.2.11 on 2022-02-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_visit_observations_visit_site_name_date_unique_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomyfamily',
            name='family',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='taxonomysuborder',
            name='suborder',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='identification',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='identification',
            constraint=models.UniqueConstraint(fields=('specimen_label', 'identification_guide', 'species', 'date_of_identification'), name='observations_identification_specimen_guide_species_date_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='plot',
            constraint=models.UniqueConstraint(fields=('visit', 'position'), name='observations_plot_visit_position_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.UniqueConstraint(fields=('visit', 'method', 'repeat'), name='observations_survey_visit_method_repeat_unique_relationships'),
        ),
    ]
