# Generated by Django 3.2.11 on 2022-01-24 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=20)),
                ('identification_notes', models.TextField(max_length=2048)),
                ('identification_guide', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('stage', models.CharField(choices=[('Adult', 'Adult'), ('Nymph', 'Nymph')], max_length=5)),
                ('confidence', models.CharField(choices=[('In_progress', 'In progress'), ('Check', 'Check'), ('Confirmed', 'Confirmed'), ('Redo', 'Redo')], max_length=11)),
                ('specimen_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.observation')),
            ],
        ),
    ]
