# Generated by Django 3.2.11 on 2022-01-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_identificationguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='identification_guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.identificationguide'),
        ),
    ]
