# Generated by Django 3.2.11 on 2022-03-09 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_add_observation_preservation_20220309_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FilePathField(max_length=300, path=None, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.observation')),
            ],
        ),
    ]
