# Generated by Django 3.2.11 on 2022-01-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxclass', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Taxonomy classes',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=255, unique=True)),
                ('taxclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.taxonomyclass')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=255, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.taxonomyorder')),
            ],
            options={
                'verbose_name_plural': 'Taxonomies',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name_english', models.CharField(blank=True, max_length=100, null=True)),
                ('common_name_catalan', models.CharField(blank=True, max_length=100, null=True)),
                ('common_name_spanish', models.CharField(blank=True, max_length=100, null=True)),
                ('latin_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='observations.taxonomy')),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.AlterField(
            model_name='identification',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.species'),
        ),
    ]
