# Generated by Django 3.2.11 on 2022-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_alter_identification_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='confidence',
            field=models.CharField(blank=True, choices=[('In_progress', 'In progress'), ('Check', 'Check'), ('Check_in_museum', 'Check in museum'), ('Confirmed', 'Confirmed'), ('Redo', 'Redo'), ('Yes', 'Yes'), ('Review', 'Review'), ('Cannot_determine_further', 'Cannot determine further'), ('Small_nymph_hard_to_ID', 'Small nymph hard to ID')], max_length=30, null=True),
        ),
    ]
