# Generated by Django 3.2.11 on 2022-05-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_alter_identification_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomySubfamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subfamily', models.CharField(max_length=255, unique=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.taxonomyfamily')),
            ],
            options={
                'verbose_name_plural': 'Taxonomy subfamilies',
            },
        ),
    ]
