# Generated by Django 3.2.11 on 2022-01-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_alter_site_20220125_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteorologyConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_coverage_start', models.IntegerField(blank=True, null=True)),
                ('wind_start', models.IntegerField(blank=True, null=True)),
                ('rain_start', models.IntegerField(blank=True, null=True)),
                ('cloud_coverage_end', models.IntegerField(blank=True, null=True)),
                ('wind_end', models.IntegerField(blank=True, null=True)),
                ('rain_end', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=2048, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.visit')),
            ],
        ),
    ]
