# Generated by Django 3.2.11 on 2022-01-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetationStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_vegetation_cover', models.IntegerField(blank=True, null=True)),
                ('percentage_bare_ground', models.IntegerField(blank=True, null=True)),
                ('percentage_rock', models.IntegerField(blank=True, null=True)),
                ('height_75percent', models.IntegerField(blank=True, null=True)),
                ('max_height', models.IntegerField(blank=True, null=True)),
                ('density_01', models.IntegerField(blank=True, null=True)),
                ('density_02', models.IntegerField(blank=True, null=True)),
                ('density_03', models.IntegerField(blank=True, null=True)),
                ('density_04', models.IntegerField(blank=True, null=True)),
                ('density_05', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=2048, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.plot')),
            ],
        ),
    ]
