# Generated by Django 3.2.11 on 2022-05-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_taxonomygenus_subfamily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomygenus',
            name='family',
        ),
    ]
