# Generated by Django 3.2.11 on 2022-01-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0012_corrections_20220125_1542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('site_name', 'date')},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='method',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('Net', 'Net'), ('Hand', 'Hand')], max_length=5, null=True)),
                ('repeat', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=2, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.visit')),
            ],
            options={
                'unique_together': {('visit', 'method', 'repeat')},
            },
        ),
    ]
