# Generated by Django 3.2.11 on 2022-05-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0015_alter_identification_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photograph',
            name='observation',
        ),
    ]
