# Generated by Django 3.2.11 on 2022-05-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0016_remove_photograph_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='observation',
            field=models.ManyToManyField(to='observations.Observation'),
        ),
    ]
