# Generated by Django 3.2.11 on 2022-05-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0017_photograph_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='filepath',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
