# Generated by Django 3.2.11 on 2022-05-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0018_alter_photograph_filepath'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='identification',
            name='observations_identification_check_confidence_reasons',
        ),
        migrations.AlterField(
            model_name='identification',
            name='confidence',
            field=models.CharField(blank=True, choices=[('In_progress', 'In progress'), ('Check', 'Check'), ('Check_in_museum', 'Check in museum'), ('Confirmed', 'Confirmed'), ('Redo', 'Redo'), ('Review', 'Review'), ('Finalised', 'Finalised')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='confidence_reason',
            field=models.CharField(blank=True, choices=[('ID_certain', 'ID certain'), ('ID_uncertain', 'ID uncertain'), ('ID_incomplete', 'ID incomplete'), ('ID_needs_confirmation', 'ID needs confirmation'), ('ID_incorrect', 'ID incorrect'), ('Cannot_determine_further', 'Cannot determine further'), ('Small_nymph_hard_to_ID', 'Small nymph hard to ID'), ('Cannot_split_further', 'Cannot split further')], max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='identification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('confidence', 'Confirmed'), ('confidence_reason__in', ('Small_nymph_hard_to_ID', 'Cannot_determine_further', 'ID_certain'))), models.Q(('confidence__in', ('Check', 'Check_in_museum')), ('confidence_reason', 'ID_needs_confirmation')), models.Q(('confidence', 'In_progress'), ('confidence_reason', 'ID_incomplete')), models.Q(('confidence', 'Review'), ('confidence_reason', 'ID_uncertain')), models.Q(('confidence', 'Redo'), ('confidence_reason', 'ID_incorrect')), models.Q(('confidence', 'Finalised'), ('confidence_reason', 'Cannot_split_further')), _connector='OR'), name='observations_identification_check_confidence_reasons'),
        ),
    ]
